<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Exam Submission PDF</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            margin: 40px;
            font-size: 14px;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
        }

        .header h1 {
            font-size: 26px;
            margin-bottom: 10px;
            border-bottom: 2px solid #4a90e2;
            padding-bottom: 5px;
        }

        .details-table {
            width: 100%;
            margin-bottom: 30px;
            border-collapse: collapse;
        }

        .details-table td {
            padding: 8px 12px;
            vertical-align: top;
        }

        .details-table td.label {
            font-weight: bold;
            width: 25%;
        }

        .question-block {
            border: 1px solid #ccc;
            border-left: 5px solid #4a90e2;
            background-color: #f5f9ff;
            padding: 15px;
            margin-bottom: 20px;
        }

        .question {
            font-weight: bold;
            margin-bottom: 8px;
            white-space: pre-line;
        }

        .answer {
            margin-left: 10px;
            line-height: 1.6;
            white-space: pre-line;
        }

        .footer {
            text-align: center;
            font-size: 11px;
            color: #777;
            margin-top: 50px;
        }
    </style>
</head>

<body>

    <div class="header">
        <h1>Exam Submission Report</h1>
    </div>

    <table class="details-table">
        <tr>
            <td class="label">Student Name:</td>
            <td>{{ $studentName }}</td>
        </tr>
        <tr>
            <td class="label">Course Name:</td>
            <td>{{ $courseName }}</td>
        </tr>
        <tr>
            <td class="label">Exam Title:</td>
            <td>{{ $examTitle }}</td>
        </tr>
        <tr>
            <td class="label">Submitted On:</td>
            <td>{{ $submittedOn }}</td>
        </tr>
    </table>

    @foreach ($questionAnswerList as $item)
        <div class="question-block">
            <div class="question">Que: {{ html_entity_decode($item['question']) }}</div>
            <div class="answer">Ans: {{ html_entity_decode($item['answer']) }}</div>
        </div>
    @endforeach

    <div class="footer">
        This document is generated by the system and does not require a signature.
    </div>

</body>

</html>
